%% DEMO: Evaluation of clusterings generated by a hierarchical algorithm
% ------------------------------------------------------------------------
% The Cluster Validity Index Tooolbox (CVIT) for automatic determination 
% of clusters from clustering solution contains more than 70 functions (m-files)
% This toolbox was developed with MATLAB R2014a.
%
% Developed by
%   Adan Jose-Garcia (adan.jose@cinvestav.mx)
%   Wilfrido Gomez Flores (wgomez@cinvestav.mx)
%
% Please, cite the following paper where this toolbox was introduced:
%
%   [PENDING]...
%
%
% IMPORTANT: First run "RUN_ME_FIRST.m" file to add this toolbox to search path.
%------------------------------------------------------------------------
clc; clear all; close all;

addpath([pwd '/proximity']);
addpath([pwd '/cvi']);
addpath([pwd '/datasets']);

% List of available cluster validity indices (CVIs)
CVInames = {'xb','ch','sf','pbm','cs',...
            'gd31','gd41','gd51','gd33','gd43',...
            'gd53','db2','db','cop','sil',...
            'dunn','sv','sym','sdunn','sdb',...
            'sdbw','cind'};

% List of available distances
Distnames = {'euc','neuc','cos','pcorr','scorr','lap'};

% List of datasets provided
DSnames = {'Data_4_3','Data_5_2','Moon', 'Iris'}; 

% ------------------------------------------------------------------------
%% Evaluate a set of clusterings generated by a hierarchical clustering algorithm

% Load the Iris dataset
load fisheriris;

% Hierarchical methods: 'single', 'complete', 'weighted', 'centroid', 'ward'
hmethod = 'average'; 
Z = linkage(meas, hmethod);

% Generation of clusterings when varying the number of clusters
Kmax = 10;
clust = zeros(size(meas,1),Kmax);
for k=1:Kmax
    clust(:,k) = cluster(Z, 'maxclust', k);
end

% Evaluation of the clustering solutions using the 'ch' index
eva = evalcvi(meas, clust, 'ch');
