%% DEMO: Evaluation of clusterings generated by a hierarchical algorithm
% ------------------------------------------------------------------------
% The Cluster Validity Index Tooolbox (CVIT) for automatic determination 
% of clusters from clustering solution contains more than 70 functions (m-files)
% This toolbox was developed with MATLAB R2014a.
%
% IMPORTANT: First run "RUN_ME_FIRST.m" file to add this toolbox to search path.
%------------------------------------------------------------------------
clc; clear all; close all;

addpath([pwd '/proximity']);
addpath([pwd '/cvi']);
addpath([pwd '/datasets']);
addpath([pwd '/validation']);
addpath([pwd '/utils']);

% List of available cluster validity indices (CVIs)
CVInames = {'xb','ch','sf','pbm','cs',...
            'gd31','gd41','gd51','gd33','gd43',...
            'gd53','db2','db','cop','sil',...
            'dunn','sv','sym','sdunn','sdb',...
            'sdbw','cind'};

% List of available distances
Distnames = {'euc','neuc','cos','pcorr','scorr','lap'};

% List of datasets provided
DSnames = {'Data_4_3','Data_5_2','Moon', 'Iris'}; 

% ------------------------------------------------------------------------
%% Evaluate a set of clusterings generated by a hierarchical clustering algorithm

cvi = CVInames{2};

% Load the Iris dataset
load fisheriris;
X = meas; T = [ones(50,1); ones(50,1)*2; ones(50,1)*3]; % Iris labels, k=3

% Hierarchical methods: 'single', 'complete', 'weighted', 'centroid', 'ward'
hmethod = 'average'; 
Z = linkage(X, hmethod);

% Generation of clusterings when varying the number of clusters
Kmax = 10;
clust = zeros(size(meas,1),Kmax);
for k=1:Kmax
    clust(:,k) = cluster(Z, 'maxclust', k);
end

% Evaluation of the clustering solutions using the 'ch' index
eva = evalcvi(meas, clust, cvi);

Kb = eva.OptimalK; % Estimated k value
Tb = clust(:,Kb);  % Estimated clustering solution
ARI_val = pairwiseindex(T,Tb)
% ------------------------------------------------------------------------
%% Figure 1: Dendrogram plot
figure(1)
dendrogram(Z,0,'colorthreshold', 1.8)
title('Iris dendrogram');
ylabel('similarity'); xlabel('data points');
ytickformat('%.1f');

niceplot(7); box on; 
set(gca,'YGrid', 'on'); set(gca,'xGrid', 'on'); 
%set(gca,'xTick',1:3:size(clust,1)); 

set(gca,'xTickLabels',{});
set(gcf, 'color','white');
set(gcf, 'renderer', 'painters');
figuresize(8,5,'centimeters');
xtickangle(45);
% ------------------------------------------------------------------------
%% Figure 2: Line plot (CVI convergence)
figure(2)
mg = [0.60 0.60 0.60]; mb =[0 0.4470 0.7410];

k_vals   = 1:Kmax;
cvi_vals = eva.FitnessValues;
plot(k_vals,cvi_vals,'-o','Color',mb,'MarkerSize',3,'LineWidth',1.5,'MarkerFaceColor',mb); hold on;

title([upper(cvi) ': Optimal number of clusters']);
xline(Kb,'Color',mg,'LineStyle','-.','LineWidth',1.5);
ylabel([upper(cvi) ' value']); xlabel('number of clusters');

niceplot(8); box on; 
set(gca,'YGrid', 'on'); set(gca,'xGrid', 'on'); 
set(gca,'xTick',2:1:Kmax, 'XLim',[2 Kmax]);
set(gcf, 'color','white');
set(gcf, 'renderer', 'painters');
figuresize(8,5,'centimeters');

% ------------------------------------------------------------------------
%% Figure 3: 2D Scatter plot w/ clusters
figure(3)
dotp = 12;
map = colormap(lines);

kT = unique(Tb);
for i = 1:numel(kT)
    idx = Tb==kT(i);
    pscat = scatter(X(idx,1),X(idx,3),dotp,'o','MarkerEdgeColor',map(i,:),'MarkerFaceColor',map(i,:));
    pscat.MarkerFaceAlpha = .2;
    pscat.MarkerEdgeAlpha = .5;
    hold on;
end
title('Iris clustering');
xlabel('sepal lenght'); ylabel('petal lenght');
txt = ['ARI = ' num2str(ARI_val,'%.2f')]; text(6,2,txt);

niceplot(8);
set(gca,'xgrid','on','ygrid','on');
%set(gca,'yTick',0:0.5:1,'xLim', [0 1]);

set(gcf, 'color','white');
set(gcf, 'renderer', 'painters');
figuresize(5,5,'centimeters');