function niceplot(fontsize)

if nargin == 0
    fontsize = 8;
end

% Legend and Tick Labels
set(gca, ...
    'FontName'      , 'Helvetica'    ,...
    'FontSize'      , fontsize-1      ,...
    'FontWeight'    , 'normal'        );


set([get(gca,'xlabel'), get(gca,'ylabel'), get(gca,'zlabel'), get(gca,'title')], ...
    'FontName'  ,'Helvetica'    ,...
    'FontSize'  , fontsize       ,...
    'FontWeight', 'bold'       );

% Box plot
set(findobj(gca,'Type','text'),'FontName','Trebuchet MS','FontSize',fontsize,'FontWeight', 'bold');

% Adjust Current Axes Properties
set(gca, ...
  'Box'         , 'on'      , ...
  'TickLength'  , [.01 .01] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'     , ...
  'ZMinorTick'  , 'off'     , ...
  'XGrid'       , 'off'     , ...
  'YGrid'       , 'off'     , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 0.8         );


%  'TickDir'     , 'out'     , ...